### PR TITLE
URL encoding for passwords, verify False for put requests and specify a git branch

### PR DESCRIPTION
**Pull request by Criptic**

### CODE REVIEW

**Comment by kaponte75** [comment]
This pull request is currently being reviewed.

**Review by wenjiesas — COMMENTED** [review]
Do we have a list of special character that we want to parse it?

**Review by wenjiesas — COMMENTED** [review]
Looks good for me.

**Review by wenjiesas — COMMENTED** [review]
Looks good.

**Comment by Criptic** [comment]
> Do we have a list of special character that we want to parse it?

The python urllib.encode.quote worked well for me. But in general it is needed to encode any character that has a meaning inside of an URL like an ampersand or a question mark, because when they are part of the password this will break the authentication.

**Pull request merged**
